[versions]
kotlin = "2.1.20"
intellijPlatform = "2.10.2"
intellijIdea = "2025.2.4"
imageioWebp = "3.12.0"
batikTranscoder = "1.19"
batikCodec = "1.19"

[libraries]
imageio-webp = { module = "com.twelvemonkeys.imageio:imageio-webp", version.ref = "imageioWebp" }
batik-transcoder = { module = "org.apache.xmlgraphics:batik-transcoder", version.ref = "batikTranscoder" }
batik-codec = { module = "org.apache.xmlgraphics:batik-codec", version.ref = "batikCodec" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
